import Head from "next/head";
import { client, getPosts } from "../../util/client";

const Home = ({ data }: any) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {data && data.map(({_id, title}: any) =>  {
            return (
              <li key={_id}>
                <b>{title}</b>
              </li>
            );
          })}
        </ul>
      </main>
    </>
  );
};

export async function getStaticProps() {
 
  const data = await getPosts();

  return {
    props: {
      data,
    },
  };
}

export default Home;
