export const defaultValue = {
  dataApplication: {},
  setDataApplication: () => {},
  question: 0,
  setQuestion: () => {},
  selectedCheckbox: [],
  setSelectedCheckbox: () => {},
  onChangeQuestion: () => {},
  feelingForm: "",
  setFeelingForm: () => {},
  commentForm: {},
  setCommentForm: () => {},
  personalDetailsForm: {
    name: "",
    address: "",
    email: "",
    phone: "",
    postcode: "",
    consent: false,
  },
  setPersonalDetailsForm: () => {},
  globalInfo: {},
  setGlobalInfo: () => {},
  contextCleaner: () => {},
};
