name: Deploy to Lambeth Heroku Production new

on:
  push:
    branches:
      - testing-heroku-deploy

jobs:
  handle-event:
    runs-on: ubuntu-latest
    environment: dsn-lambeth-production

    steps:
      # - name: Handle repository dispatch event new
      #   run: |
      #     echo "Received repository dispatch event new"
      #     echo "${{ github.event.client_payload.description }}"

      - uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Login to Heroku container registry
        run: echo ${{ secrets.LAMBETH_HEROKU_API_KEY }} | docker login -u _ --password-stdin registry.heroku.com

      - name: Build the Docker image
        run: |
          docker build \
          --build-arg ARG_NEXT_PUBLIC_SANITY_PROJECT_ID=${{secrets.LAMBETH_NEXT_PUBLIC_SANITY_PROJECT_ID}} \
          --build-arg ARG_NEXT_PUBLIC_SANITY_DATASET=${{ secrets.LAMBETH_NEXT_PUBLIC_SANITY_DATASET }} \
          --build-arg LAMBETH_NEXT_PUBLIC_SANITY_SECRET_TOKEN=${{secrets.LAMBETH_NEXT_PUBLIC_SANITY_SECRET_TOKEN}} \
          -t registry.heroku.com/${{ secrets.LAMBETH_HEROKU_APP_NAME }}/web .

      - name: Tag the Docker image
        run: docker tag registry.heroku.com/${{ secrets.LAMBETH_HEROKU_APP_NAME }}/web registry.heroku.com/${{ secrets.LAMBETH_HEROKU_APP_NAME }}/web

      - name: Push the Docker image
        run: docker push registry.heroku.com/${{ secrets.LAMBETH_HEROKU_APP_NAME }}/web

      - name: Release the Docker image
        run: |
          heroku container:release web --app ${{ secrets.LAMBETH_HEROKU_APP_NAME }}

      - name: Notify on successful deployment
        if: success()
        run: echo "Deployment to dsn-lambeth-production successful!"
