name: Automated Accessibility Tests

on:
  pull_request:
    branches: [staging]

env:
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.TEST_ENV_SANITY_PROJECT_ID }}
  NEXT_PUBLIC_SANITY_SECRET_TOKEN: ${{ secrets.TEST_ENV_SANITY_TOKEN }}
  NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.TEST_ENV_SANITY_DATASET }}
  NEXT_PUBLIC_API_MOCKING: enabled
  NODE_ENV: test

jobs:
  pa11y:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          yarn install
          yarn global add pa11y-ci wait-on

      - name: Initialize MSW
        run: yarn msw:init

      - name: Build the application
        run: yarn build

      - name: Start the application
        run: |
          yarn start > app.log 2>&1 &
          echo $! > pid.txt

      - name: Wait for the application to start
        run: wait-on http://localhost:3000 -t 60000

      - name: Run Pa11y
        run: pa11y-ci

      - name: Stop the application
        if: always()
        run: kill $(cat pid.txt)

      - name: Output application logs on failure
        if: failure()
        run: cat app.log
