name: Dev branch updated

on:
  push:
    branches:
      - fix/deployment-workflow

permissions: write-all

jobs:
  send-event:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch event
        run: |
          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ secrets.DEPLOYMENT_TARGET_OWNER }}/${{ secrets.DEPLOYMENT_TARGET_REPO }}/dispatches \
            -d '{"event_type":"code_update_develop","client_payload":{"description":"develop branch has been updated"}}')
          http_code="${response: -3}"
          response_body="${response::-3}"
          echo "Response code: $http_code"
          echo "Response body: $response_body"
          if [ "$http_code" -ne 200 ]; then
            echo "Failed to send repository dispatch event"
            exit 1
          fi
        continue-on-error: false
