name: Dev branch updated

on:
  push:
    branches:
      - fix/deployment-workflow

permissions:
  permissions: write-all

jobs:
  send-event:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch event
        run: |
          echo "https://api.github.com/repos/${{ secrets.DEPLOYMENT_TARGET_OWNER }}/${{ secrets.DEPLOYMENT_TARGET_REPO }}/dispatches"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ secrets.DEPLOYMENT_TARGET_OWNER }}/${{ secrets.DEPLOYMENT_TARGET_REPO }}/dispatches \
            -d '{"event_type":"code_update_develop","client_payload":{"description":"develop branch has been updated"}}'
